			$(document).ready(function(){
  				$(".firstone").click(function(){
    			$(".FirstPic").css("display","block");
    			$(".textone").css("font-weight","bolder");
    			$(".textone").css("color","rgb(1,152,229)");
    			$(".texttwo").css("font-weight","inherit");
    			$(".texttwo").css("color","rgb(213,213,213)");
    			$(".TwoPic").css("display","none");
 	 		});
 	 			$(".firsttwo").click(function(){
    			$(".FirstPic").css("display","none");
    			$(".textone").css("font-weight","inherit");
    			$(".textone").css("color","rgb(213,213,213)");
    			$(".texttwo").css("font-weight","bolder");
    			$(".texttwo").css("color","rgb(1,152,229)");
    			$(".TwoPic").css("display","block");
 	 		});
 	 		
 	 		$(".firstone2").click(function(){
    			$(".FirstPic2").css("display","block");
    			$(".textone2").css("font-weight","bolder");
    			$(".textone2").css("color","rgb(1,152,229)");
    			$(".texttwo2").css("font-weight","inherit");
    			$(".texttwo2").css("color","rgb(213,213,213)");
    			$(".TwoPic2").css("display","none");
 	 		});
 	 			$(".firsttwo2").click(function(){
    			$(".FirstPic2").css("display","none");
    			$(".textone2").css("font-weight","inherit");
    			$(".textone2").css("color","rgb(213,213,213)");
    			$(".texttwo2").css("font-weight","bolder");
    			$(".texttwo2").css("color","rgb(1,152,229)");
    			$(".TwoPic2").css("display","block");
 	 		});
			});